# Generated by Django 5.0.2 on 2024-12-17 23:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='uploads/resumes/')),
                ('impact_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quantitative_impact_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantitative_impact_analysis', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-created_at'],
            },
        ),
    ]
