# Generated by Django 5.0.2 on 2024-12-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0002_rename_quantitative_impact_analysis_resume_active_voice_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='overall_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='overall_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
