# Generated by Django 5.0.2 on 2024-12-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0003_resume_overall_feedback_resume_overall_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
