# Generated by Django 5.0.2 on 2024-12-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default_avatar.jpg', upload_to='uploads/avatars'),
        ),
    ]
